config/routes.rb
Rails.application.routes.draw do
  

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' =>  'cart#add'

  resources :userdetils
  resources :quantities

  resources :products do
    resources :comments
  end    

  root 'visitor#index'
  devise_for :users

     get '/index' => 'visitor#index'
     get '/contact' => 'visitor#contact'
     get '/about' => 'visitor#about'

     get '/blog-grid' => 'home#blog-grid'
     get '/blog-sidebar' => 'home#blog-sidebar'
     get '/blog-single' => 'home#blog-single'
     get '/cart' => 'home#cart'
     get '/checkout' => 'home#checkout'
     get '/event' => 'home#event'
     get '/menu' => 'home#menu'
     get '/reservation' => 'home#reservation'
     get '/shop-2' => 'home#shop-2'
     get '/shop' => 'home#shop' 
     get '/product-detail-popup' => 'home#product-detail-popup'
     get '/shortcode' => 'home#shortcode'
               

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	 before_action :authenticate_user!
	def add
		id = params[:id]

		if session[:cart] then
		 cart = session[:cart]
		else
			session[:cart] ={}
			cart = session[:cart]
		end
		
		if cart[id] then
		   cart[id] = cart[id] +1
		else
		   cart [id] =1
		end
		redirect_to :action => :index  	
	end

 def clearCart
 	session[:cart] = nil
 	redirect_to :action => :index
 	
 end

  def index
  	if session[:cart] then
  		@cart= session[:cart]
  	else
  		@cart = {}
  	end		

  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<!-- 

<h1>My Cart</h1>


<%= link_to 'Empty Your Cart', cart_clear_path	%>


<br><br><br>

<div class="container">
  <h2>Table</h2>
 
<% total = 0 %>
  <div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>product name</th>
        <th>product type</th>
        <th>discription</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
    <% @cart.each do | id, quantity | %>
     <% product = Product.find_by_id(id) %>	
      <tr>
    <td>   <%= link_to (image_tag product.image.url(:thumb)), product%></td>
	<td><%= link_to product.product_name, product%></td>
	<td><%= link_to product.product_type, product%></td>
	<td><%= link_to product.info, product%></td>
	<td><%= quantity%></td>
	<td><%= number_to_currency(product.price, :unit => 'Rs.')%></td>
       <% total +=  quantity *  product.price %>
      </tr>
      <%end%>
    </tbody>
  </table>
	<strong>TOTAL AMOUNT IS = &nbsp<%= number_to_currency(total, :unit => 'Rs.') %></strong>
  </div>
</div>
<br>
</body>
 -->



<!DOCTYPE html>
 <html > 

<head>
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    
    <title>food</title>
</head>
<body>

 	<CENTER><h1>SHOPING CART</h1></CENTER>
 	<hr>
 		

			



<div class="container-fluid">
   <div class="row">
  <div class="col-sm-2">
    <% if @cart.empty?%>
        <p>Your Cart Is Currently Empty.</p>
      <%else%>
      <%= link_to 'Empty My Cart', cart_clear_path, :class=>"btn text-uppercase"  %>
      <%end%>
  </div>
  <div class="col-sm-2">
   <%= link_to 'SHOP', products_path, :class=>"btn text-uppercase" %> 
  </div>
  <div class="row">

    <div class="col-sm-9 col-md-6 col-lg-8" style="background-color:#FFFFFF;">
     
     <div class="container">
 
					<div class="container">
						<% total = 0 %>
						  <div class="table-responsive">          
						  <table class="table table-hover">
						    <thead>
						      <tr>
						        <th>YOUER SHOPING BAG</th>
						        <!-- <th>product name</th>
						        <th>product type</th>
						        <th>discription</th>
						        <th>Quantity</th> -->
						        <th></th>
						        <th>Price</th>
						      </tr>
						    </thead>
						    <tbody>
						    <% @cart.each do | id, quantity | %>
						     <% product = Product.find_by_id(id) %>	
						      <tr>
						    <td> <%= link_to (image_tag product.image.url(:thumb)), product%></td>
							  <td><b><%= product.product_name%></b><br>
								 <b>Item id:</b>&nbsp<%= product.id%><br>
								 <b>Type:</b>&nbsp<%=product.product_type%><br>
								 <b>Quantity:</b>&nbsp<%= quantity%>
								</td>





							<!-- <td>Type:&nbsp<%= link_to product.product_type, product%></td>
							<td><%= link_to product.info, product%></td>
							<td><%= quantity%></td> -->
							<td><%= number_to_currency(product.price, :unit => 'Rs.')%></td>
						       <% total +=  quantity *  product.price %>
						      </tr>
						      <%end%>
						    </tbody>
						  </table>
							
           
						  </div>
						</div>
						</div>

  			  </div>
               <div class=" col-sm-3 col-md- col-lg-4" style="background-color:#D8D2CA;">
                    <table class="table ">
                           <thead>
                             <tr>
                               <th>SUMMARY</th>
                              
                              </tr>
                           </thead>
                           <tbody>
                               <tr>
                                 <td><b>SUBTOTAL</b></td>
                                 <td>--</td>
                                 <td><b><%= number_to_currency(total, :unit => 'Rs.') %></b></td>
                               </tr>
                               <tr>
                                 <td>Duties</td>
                                 <td>--</td>
                                 <td>0</td>
                               </tr>
                               <tr>
                                 <td>Shipping</td>
                                 <td>--</td>
                                 <td>0</td>
                               </tr>
                               <tr>
                                 <td>Discount</td>
                                 <td>--</td>
                                 <td>0</td>
                               </tr>
                               <tr>
                                 <td>Tax</td>
                                 <td>--</td>
                                 <td>0</td>
                               </tr>
                                <tr>
                                 <td> <strong>TOTAL AMOUNT IS:</strong></td>
                                 <td>--</td>
                                 <td> <strong><%= number_to_currency(total, :unit => 'Rs.') %></strong></td>
                               </tr>
                               

                		</tbody>
  				</table>
                              	<center><%= link_to 'Continue', cart_clear_path, :class=>"btn text-uppercase"%></center>
    

    </div>
  </div>
</div>


<br><br><br><br>