config/routes.rb
Rails.application.routes.draw do
  

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' =>  'cart#add'

  resources :userdetils
  resources :quantities

  resources :products do
    resources :comments
  end    

  root 'visitor#index'
  devise_for :users

     get '/index' => 'visitor#index'
     get '/contact' => 'visitor#contact'
     get '/about' => 'visitor#about'

     get '/blog-grid' => 'home#blog-grid'
     get '/blog-sidebar' => 'home#blog-sidebar'
     get '/blog-single' => 'home#blog-single'
     get '/cart' => 'home#cart'
     get '/checkout' => 'home#checkout'
     get '/event' => 'home#event'
     get '/menu' => 'home#menu'
     get '/reservation' => 'home#reservation'
     get '/shop-2' => 'home#shop-2'
     get '/shop' => 'home#shop' 
     get '/product-detail-popup' => 'home#product-detail-popup'
     get '/shortcode' => 'home#shortcode'
               

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                 :integer          not null, primary key
#  product_name       :string(255)
#  product_type       :string(255)
#  price              :integer
#  info               :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  user_id            :integer
#



class Product < ActiveRecord::Base
	has_attached_file :image, :styles => { :large => "600x600>",:medium => "300x300>", :thumb => "150x150>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	


	has_many :comments, dependent: :destroy
	belongs_to :user
	before_create :randomize_id



private
def randomize_id
  begin
    self.id = SecureRandom.random_number(1_0_000)
  end 
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end
    # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
     @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :product_type, :price, :info, :image, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
 <%= form_for @product, :html=>{:class=>"form-horizontal" ,:role=>"form"} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">image
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_field :product_type %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product type</th>
      <th>Price</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 -->
<!--   <tbody>
    <% @products.each do |product| %>
      <tr>
       <td><%= image_tag product.image.url(:medium) %></td>
        <td><%= product.product_name %></td>
        <td><%= product.product_type %></td>
        <td><%= product.price %></td>
        <td><%= product.info %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %> -->

<!DOCTYPE html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">

    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

 
    
    <title>food</title>
</head>
<body>


<!-- PAGE WRAP -->
<div id="page-wrap">
    
    

    <!-- SUB BANNER -->
   <!--  <section class="sub-banner text-center section">
        <div class="awe-parallax bg-4"></div>
        <div class="awe-title awe-title-2">
            <h3 class="lg text-uppercase">Shop</h3>
        </div>
    </section> -->
    <!-- END / SUB BANNER -->

    <!-- SHOP PAGE -->
    <section id="shop-page" class="shop-page section">
        <div class="tabs-shop tabs-page">
            <div class="container">
                <ul class="nav-tabs" role="tablist">
                    <li class="active"><a href="#breakfast" role="tab" data-toggle="tab">Breakfast</a></li>
                    <li><a href="#lunch" role="tab" data-toggle="tab">Lunch</a></li>
                    <li><a href="#dinner" role="tab" data-toggle="tab">Dinner</a></li>
                </ul>
                
                <select class="select-custom" name="">
                    <option value="">All Meals</option>
                    <option value="">Breakfast</option>
                    <option value="">Lunch</option>
                </select>
            </div>
        </div>
        <div class="section-content">
            <div class="container">
                <div class="tab-shop-content tab-content">
                    <!-- BREAKFAST -->
                    <div class="tab-pane fade in active" id="breakfast">
                        <div class="row">



                            <!-- THE MENU ITEM -->
                           <% @products.each do |product| %>
                            <div class="col-sm-6 col-md-4 col-lg-3">
                                <div class="product-item">
                                    <div class="image-wrap">
                                        <a class="pp-product-detail" href="product">
                                       <!--     <%=  image_tag product.image.url(:large) ,:alt=>"" %> 
                                           <%= link_to 'Show', product %> -->
                                           <%= link_to product do %>
                                               <%= image_tag product.image.url(:large)%>
                                            <% end %>
                                        </a>
                                    </div>
                                    <div class="product-body">
                                        <div class="item-price">
                                            <span class="amount"><%= number_to_currency(product.price, :unit => 'Rs.') %></span>
                                        </div>
                                        <div class="item-name">
                                            <h4 class="sm">
                                                <a class="pp-product-detail" href="product_detail">
                                                 <%= link_to product do %>
                                                 <%= product.product_name %>
                                                 <%end%>
                                                 </a>
                                            </h4>
                                        </div>
                                        <div class="categories">
                                            <ul>
                                                <li><a href="#"><i class="icon awe_check"></i>
                                                 <%= link_to product do %>
                                                 <%= product.product_type %></a></li>
                                                 <%end%>  
                                                <li><a href="#"><i class="icon awe_check"></i>
                                                 <%= link_to product do %>
                                                 <%= product.info %></a></li>
                                                 <li><a href="/cart/<%= product.id%>">Add to cart</a> </li>  
                                                 <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %> </li>
                                                <%end%>
                                            </ul>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                            <% end %>
                            <!-- END / THE MENU ITEM -->
                           


                            <!-- THE MENU ITEM -->
                           <!--  <div class="col-sm-6 col-md-4 col-lg-3">
                                <div class="product-item">
                                    <div class="image-wrap">
                                        <a class="pp-product-detail" href="product-detail.html">
                                            <img src="assets/blog/img-3.jpg" alt="">
                                        </a>
                                    </div>
                                    <div class="product-body">
                                        <div class="item-price">
                                            <span class="amount">$12</span>
                                        </div>
                                        <div class="item-name">
                                            <h4 class="sm">
                                                <a class="pp-product-detail" href="product-detail.html">Cereal Strawbery & Milk</a>
                                            </h4>
                                        </div>
                                        <div class="categories">
                                            <ul>
                                                <li><a href="#"><i class="icon awe_check"></i>Healthy food</a></li>
                                                <li><a href="#"><i class="icon awe_check"></i>Low-carb</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div> -->
                            <!-- END / THE MENU ITEM -->
                        </div>
                        
                    </div>
                    <!-- END / DINNER -->

                </div>
            </div>
        </div>
    </section>
    <!-- END / SHOP PAGE -->
   

</div>
<!-- END / PAGE WRAP -->




</body>

</html>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!-- <p id="notice"><%= notice %></p>
<%= @product.inspect %>
<p>
  <strong>Product image:</strong>
  <%= image_tag @product.image.url(:medium) %>
</p>
<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @product.product_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Info:</strong>  `
  <%= @product.info %>
</p> -->
<!--
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
-->

<html>
<head>

  

    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

 
    
    <title>food</title>
</head>
<body>

 <section id="contact" class="contact section">
        <div class="contact-form contact-form-2">
            <div class="divider divider-2"></div>
            <div class="container">
                  <div class="row">
                      <div class="col-md-4">
                      <address class="find-us">
                          <div class="item"> 
                          <%= image_tag @product.image.url(:large) %></div>
                          </address>
                      </div>
                      <div class="col-md-7">
                        <div class="form-row">
                          <div class="product-detail-content">
                          <h3 class="lg"> <%= @product.product_name %></h3>
                          <div class="categories">
                              <ul>
                              <li>Food Type : &nbsp;<i class="icon awe_check"></i> <%= @product.product_type %></li>
                                  
                              </ul>
                          </div>
                          <div class="product-desc">
                             
                              <div class="ingredient">
                                  <p><strong>Description :</strong> <%= @product.info %>.</p>
                                  
                              </div>
                          </div>

                          <div class="product-desc">
                             
                              <div class="ingredient">
                                  <p><strong>Quantity :</strong> </p>
                                   <select name="post[@product_id]">
                                  <option value="">Please select</option>
                                  <option value="1" selected="selected">1</option>
                                  <option value="2">2</option>
                                  <option value="3">3</option>
                                  <option value="4">4</option>
                                  <option value="5">5</option>
                                </select>
                                  
                              </div>
                          </div>

                          <div class="product-foot ">
                          <span class="price"> Rs.<%= @product.price %></span>
                          </div>
                          
                          <div class="clearfix"></div>
                          <div class="product-foot">
                             <div class="add-to-cart">
                              <%= link_to 'Back', products_path, :class=>"btn text-uppercase" %>
                               <%= link_to 'Proceed', userdetils_path, :class=>"btn text-uppercase" %>
                               <a href="/cart/<%= @product.id%>"class="btn text-uppercase">Add to cart</a>
                             
                              </div>
                          </div>
                          <br>

                      </div>
                            </div>
                      </div> 
                      
                  
                    <div class="col-md-9 ">
                        <h4 class="text-uppercase"><%= @product.comments.count %> &nbsp;Comments</h4>
                        <hr class="_hr_dark">

                        <blockquote class="blockquote q-left">
                            <%= render @product.comments %>
                          <br>  
                       </blockquote>
                       <hr class="_hr_dark">
                        <blockquote class="blockquote q-right">
                           <span class="blockquote-footer pull-left">Add a comment:</span>
                            <%= render "comments/form" %>
                        </blockquote>
                    </div>
              
                  </div>
            </div>
        </div>

</section>

</body>
</html>
<br><br><br><br><br><br>