config/routes.rb
Rails.application.routes.draw do
  

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' =>  'cart#add'

  resources :userdetils
  resources :quantities

  resources :products do
    resources :comments
  end    

  root 'visitor#index'
  devise_for :users

     get '/index' => 'visitor#index'
     get '/contact' => 'visitor#contact'
     get '/about' => 'visitor#about'

     get '/blog-grid' => 'home#blog-grid'
     get '/blog-sidebar' => 'home#blog-sidebar'
     get '/blog-single' => 'home#blog-single'
     get '/cart' => 'home#cart'
     get '/checkout' => 'home#checkout'
     get '/event' => 'home#event'
     get '/menu' => 'home#menu'
     get '/reservation' => 'home#reservation'
     get '/shop-2' => 'home#shop-2'
     get '/shop' => 'home#shop' 
     get '/product-detail-popup' => 'home#product-detail-popup'
     get '/shortcode' => 'home#shortcode'
               

end

app/models/userdetil.rb
# == Schema Information
#
# Table name: userdetils
#
#  id         :integer          not null, primary key
#  fname      :string(255)
#  lname      :string(255)
#  address    :string(255)
#  city       :string(255)
#  state      :string(255)
#  zipcode    :string(255)
#  mobileno   :string(255)
#  landlineno :string(255)
#  emailid    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Userdetil < ActiveRecord::Base

	belongs_to :user

	before_create :randomize_id

	private
	def randomize_id
	  begin
	    self.id = SecureRandom.random_number(1_000_000)
	  end 
	end
	
end

app/controllers/userdetils_controller.rb
class UserdetilsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_userdetil, only: [:show, :edit, :update, :destroy]

  # GET /userdetils
  # GET /userdetils.json
  def index
    @userdetils = current_user.userdetil.all
       if Userdetil.where(:user_id => current_user.id).present?
               userdetils_path
       else
             redirect_to new_userdetil_path
       end
  end

  # GET /userdetils/1
  # GET /userdetils/1.json
  def show
  end

  # GET /userdetils/new
  def new
    @userdetil =  Userdetil.new
  end

  # GET /userdetils/1/edit
  def edit
  end

  # POST /userdetils
  # POST /userdetils.json
  def create
    @userdetil = Userdetil.new(userdetil_params)
    @userdetil.user_id = current_user.id
    respond_to do |format|
      if @userdetil.save
         UserNotifier.send_signup_email(@userdetil).deliver_now
        format.html { redirect_to userdetils_path, notice: 'Userdetil was successfully created.' }
        format.json { render :show, status: :created, location: userdetils_path }
      else
        format.html { render :new }
        format.json { render json: @userdetil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userdetils/1
  # PATCH/PUT /userdetils/1.json
  def update
    respond_to do |format|
      if @userdetil.update(userdetil_params)
        format.html { redirect_to userdetils_path, notice: 'Userdetil was successfully updated.' }
        format.json { render :show, status: :ok, location: userdetils_path }
      else
        format.html { render :edit }
        format.json { render json: @userdetil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userdetils/1
  # DELETE /userdetils/1.json
  def destroy
    @userdetil.destroy
    respond_to do |format|
      format.html { redirect_to userdetils_url, notice: 'Userdetil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userdetil
      @userdetil = Userdetil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userdetil_params
      params.require(:userdetil).permit(:fname, :lname, :address, :city, :state, :zipcode, :mobileno, :landlineno,:emailid , :user_id)
    end
end

app/helpers/userdetils_helper.rb
module UserdetilsHelper
end

app/views/userdetils/_form.html.erb
<!-- <%= form_for(@userdetil) do |f| %>
  <% if @userdetil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userdetil.errors.count, "error") %> prohibited this userdetil from being saved:</h2>

      <ul>
      <% @userdetil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :mobileno %><br>
    <%= f.text_field :mobileno %>
  </div>
  <div class="field">
    <%= f.label :landlineno %><br>
    <%= f.text_field :landlineno %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->


<!DOCTYPE html>
<html class="" lang="en"> 
<head>
   

    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    
    <title>food</title>
</head>
<body>



<!-- PAGE WRAP -->
<div id="page-wrap">
    
    
  

    <!-- CONTACT US -->
    <section id="contact" class="contact section">

        <div class="contact-form contact-form-2">
            <div class="divider divider-2"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-4 find-us">
                    <h3>Add Address info</h3>
                    <img src="../../assets/address.png"  width="250" height="42">
                      <!-- <img src="../assets/contact_us.png"  width="200" height="42"> -->
                           
                    
                    </div>
                    <div class="col-md-7">
                        <div class="form-row ">
                       
                  
                                <%= form_for(@userdetil) do |f| %>
                               <% if @userdetil.errors.any? %>
                                 <div id="error_explanation">
                                   <h2><%= pluralize(@userdetil.errors.count, "error") %> prohibited this userdetil from being saved:</h2>
                             
                                       <ul>
                                       <% @userdetil.errors.full_messages.each do |message| %>
                                         <li><%= message %></li>
                                       <% end %>
                                       </ul>
                                     </div>
                                   <% end %>
                                       <div class="form-item form-type-name">
                                          <%= f.text_field :fname, :placeholder=>"first name" %>
                                       </div>
                                        <div class="form-item form-type-name">
                                       
                                        <%= f.text_field :lname, :placeholder=>"last name"  %>
                                      </div>
                                       <div class="form-item form-textarea">
                                       
                                        <%= f.text_area :address,:placeholder=>"Address"  %>
                                      </div>
                                        <div class="form-item form-type-name">
                                     
                                        <%= f.text_field :city,:placeholder=>"city"  %>
                                      </div>
                                        <div class="form-item form-type-name">
                                       
                                        <%= f.text_field :state,:placeholder=>"state"%>
                                      </div>
                                        <div class="form-item form-type-name">
                                      
                                        <%= f.text_field :zipcode,:placeholder=>"zipcode"%>
                                      </div>
                                        <div class="form-item form-type-name">
                                        
                                        <%= f.text_field :mobileno, :placeholder=>"mobileno"%>
                                      </div>
                                        <div class="form-item form-type-name">
                                       
                                        <%= f.text_field :landlineno, :placeholder=>"landlineno"%>
                                         </div>
                                          <div class="form-item form-type-name">
                                       
                                        <%= f.text_field :emailid, :placeholder=>"Email id"%>
                                         </div>
                                                           
                          <hr>
                             <center>
                                <div >
                                     <%= f.submit value="Submit", :class=>"btn text-uppercase" %>
                                </div>
                                </center>
                            </form>
                            <%end%>
                        </div>
                    </div>
                </div>
            </div>
        </div>

       

    </section>

    <!-- END / CONTACT US -->

</div>
<!-- END / PAGE WRAP -->


</body>


</html>

app/views/userdetils/edit.html.erb
<!-- <h1>Editing Userdetil</h1>
 -->
<%= render 'form' %>

<!-- <%= link_to 'Show', @userdetil %> |
<%= link_to 'Back', userdetils_path %> -->

app/views/userdetils/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Userdetils</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Mobileno</th>
      <th>Landlineno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userdetils.each do |userdetil| %>
      <tr>
        <td><%= userdetil.fname %></td>
        <td><%= userdetil.lname %></td>
        <td><%= userdetil.address %></td>
        <td><%= userdetil.city %></td>
        <td><%= userdetil.state %></td>
        <td><%= userdetil.zipcode %></td>
        <td><%= userdetil.mobileno %></td>
        <td><%= userdetil.landlineno %></td>
        <td><%= link_to 'Show', userdetil %></td>
        <td><%= link_to 'Edit', edit_userdetil_path(userdetil) %></td>
        <td><%= link_to 'Destroy', userdetil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br> -->
 

<!-- <%= link_to 'New Userdetil', new_userdetil_path, :class=>"btn text-uppercase"  %> -->



<!DOCTYPE html>
<html class="" lang="en"> 
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">

    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

    
    <title>food</title>
</head>
<body>



<!-- PAGE WRAP -->
<div id="page-wrap">
    
    
  

    <!-- CONTACT US -->
    <section id="contact" class="contact section">

        <div class="contact-form contact-form-2">
            <div class="divider divider-2"></div>
            <div class="container">
                <div class="row">
                  <div class="col-md-3 find-us" >
                    
                        <div class="form-row">
                          <!--  <img src="../../assets/online-payment.jpg"  width="550"  >    -->
                      
                           <img src="../../assets/psc-logo-2015.png"  width="550"  >  
                           
                        </div>
                        </div>
                <% @userdetils.each do |userdetil| %>
                    <div class="col-md-5">
                        <address class="find-us">
                            <span class="md">Address</span>
                             
                            <div class="location-1">
                                <i class="icon awe_map_marker"></i>
                              <strong>Name:&nbsp&nbsp<%= userdetil.fname %>&nbsp<%= userdetil.lname %>,<br>
                               <i class="icon awe_map_marker"></i><%= userdetil.address %>,&nbsp<%= userdetil.city %>,
                               <br><%= userdetil.state %> ,&nbsp<%= userdetil.zipcode %>.<strong>

                           </div>

                            <div class="location-1">
                              
                                <strong>Mobile no :&nbsp<i class="fa fa-mobile"></i>&nbsp <%= userdetil.mobileno %>.<br>  
                                       Landline no: &nbsp<i class="fa fa-phone"></i>&nbsp<%= userdetil.landlineno %>.</strong>
                              
                            </div>
                             <div class="location-1">
                              
                                <strong>Email Id :&nbsp<i class="fa fa-mobile"></i>&nbsp <%= userdetil.emailid %>.<br>  
                                       
                            </div>
<!-- 
<!-- 
                            <div class="phone">                
                                <strong>Office No.</strong>
                                <%= userdetil.mobileno %>
                                  <strong>MObile No.</strong>
                                 <%= userdetil.landlineno %>
                            </div> -->
                            <td><%= link_to 'Edit', edit_userdetil_path(userdetil), :class=>"btn text-uppercase" %></td>
                            <td><%= link_to 'Destroy', userdetil, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn text-uppercase" %></td>
                            <td><%= link_to 'Pay', userdetils_path, :class=>"btn text-uppercase" %></td>
                        </address>
                    </div>
                    <%end%>
                         <div class="col-md-4 " >
                    
                        <div class="form-row">
                           <img src="../../assets/online-payment.jpg"  width="550"  >   
                      
                           
                           
                        </div>
                        </div>
                        
                </div>
            </div>
        </div>


    </section>

      
    <!-- END / CONTACT US -->

</div>
<!-- END / PAGE WRAP -->


</body>


</html>

app/views/userdetils/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', userdetils_path %>

app/views/userdetils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @userdetil.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @userdetil.lname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @userdetil.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @userdetil.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @userdetil.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @userdetil.zipcode %>
</p>

<p>
  <strong>Mobileno:</strong>
  <%= @userdetil.mobileno %>
</p>

<p>
  <strong>Landlineno:</strong>
  <%= @userdetil.landlineno %>
</p>

<%= link_to 'Edit', edit_userdetil_path(@userdetil) %> |
<%= link_to 'Back', userdetils_path %>